// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 * - create an ordered group of docs
 * - render a sidebar for each doc of that group
 * - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // Profile section
  profileSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'intro',
    },
  ],

  // Tooling Docs section
  toolingSidebar: [
    {
      type: 'category',
      label: 'Hoppscotch Documentation',
      items: [
        'documentation-tooling/intro',
        'documentation-tooling/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'documentation-tooling/api-reference/get-collections',
            'documentation-tooling/api-reference/post-requests',
          ],
        },
      ],
    },
  ],

  // AI Documentation section
  aiDocsSidebar: [
    {
      type: 'category',
      label: 'AI Documentation',
      items: [
        'ai-documentation/README',
        'ai-documentation/model_card',
        'ai-documentation/final_doc',
        'ai-documentation/ai_output',
        'ai-documentation/prompt_used',
        'ai-documentation/reflection',
      ],
    },
  ],

  // Web3 Documentation section
  web3DocsSidebar: [
    {
      type: 'category',
      label: 'Web3 Documentation',
      items: [
        'web3-documentation/README',
        'web3-documentation/user-guide',
      ],
    },
  ],

  
  devopsCloudSidebar: [
    {
      type: 'category',
      label: 'DevOps & Cloud',
      items: [
        'devops-cloud-documentation/overview',
        'devops-cloud-documentation/setup',
        'devops-cloud-documentation/step_by_step',
        'devops-cloud-documentation/troubleshooting',
        'devops-cloud-documentation/summary',
        'devops-cloud-documentation/reflection',
      ],
    },
  ],

  // API Docs generated from OpenAPI plugin
  apiSidebar: [
    {
      type: 'category',
      label: 'ChiMoney Api Documentation',
      items: [
        'api-documentation/intro',
        'api-documentation/Getting Started with the Chimoney API',
        {
          type: 'link',
          label: 'Interactive API Explorer',
          href: 'https://noibisjunior.github.io/writetech-accelerator-portfolio-AbdulSalaam',
        },
        {
          type: 'category',
          label: 'API Reference',
          link: {
            type: 'generated-index',
            title: 'API Reference',
            description: 'Browse the automatically generated API docs from the OpenAPI spec.',
            slug: '/api-documentation/reference',
          },
          items: [
            {
              type: 'autogenerated',
              dirName: 'api-documentation/reference',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;

// apiSidebar: [
//     {
//       type: 'category',
//       label: 'ChiMoney Api Documentation',
//       items: [
//         'api-documentation/intro',
//         'api-documentation/Getting Started with the Chimoney API',
//         {
//           type: 'link',
//           label: 'Interactive API Explorer',
//           href: '/api-explorer',
//         },
//         {
//           type: 'category',
//           label: 'API Reference',
//           link: {
//             type: 'generated-index',
//             title: 'API Reference',
//             description: 'Browse the automatically generated API docs from the OpenAPI spec.',
//             slug: '/api-documentation/reference',
//           },
//           items: [
//             {
//               type: 'autogenerated',
//               dirName: 'api-documentation/reference',
//             },
//           ],
//         },
//       ],
//     },
//   ],
// };

// export default sidebars;
