// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

 /**
  * Creating a sidebar enables you to:
  * - create an ordered group of docs
  * - render a sidebar for each doc of that group
  * - provide next/previous navigation
  *
  * The sidebars can be generated from the filesystem, or explicitly defined here.
  *
  * Create as many sidebars as you want.
  *
  * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
  */
const sidebars = {
  // Example: Autogenerated sidebar
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // Profile section
  profileSidebar: [
    {
      type: 'doc',
      label: 'Overview',
      id: 'intro',
    },
  ],

  // Tooling Docs section
  toolingSidebar: [
    {
      type: 'category',
      label: 'Hoppscotch Documentation',
      items: [
        'documentation-tooling/intro',
        'documentation-tooling/getting-started',
        {
          type: 'category',
          label: 'API Reference',
          items: [
            'documentation-tooling/api-reference/get-collections',
            'documentation-tooling/api-reference/post-requests',
          ],
        },
      ],
    },
  ],

  // API Docs generated from OpenAPI plugin
  apiSidebar: [
    {
      type: 'category',
      label: 'ChiMoney Api Documentation',
    items: [
        'api-documentation/intro',
        'api-documentation/Getting Started with the Chimoney API',
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        title: 'API Reference',
        description: 'Browse the automatically generated API docs from the OpenAPI spec.',
        slug: '/api-documentation/reference',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'api-documentation/reference', // 👈 plugin will fill this with OpenAPI endpoints
        },
      ],
    },
  ],
    },
  ],  
};

export default sidebars;
