name: OpenAPI Validation & Docs Deployment

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  validate-openapi:
    name: Validate OpenAPI Specs with Spectral
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Spectral
        run: npm install -g @stoplight/spectral-cli

      - name: Lint OpenAPI files
        run: |
          # Lint all YAML files under docs/docs-automation/ folder
          for file in docs/docs-automation/*.yaml; do
            echo "Linting $file"
            spectral lint "$file"
          done

  generate-docs:
    name: Generate & Deploy API Docs
    runs-on: ubuntu-latest
    needs: validate-openapi
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    permissions:
      contents: write
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install Redocly CLI
        run: npm install -g @redocly/cli

      - name: Build API Reference docs
        run: |
          mkdir -p docs
          redocly build-docs docs/docs-automation/openapi.yaml -o docs/api-reference.html

      - name: Create landing index.html
        run: |
          cat > docs/index.html << 'EOF'
          <!DOCTYPE html>
          <html lang="en">
          <head>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1.0">
            <title>API Documentation</title>
          </head>
          <body>
            <h1>Welcome to the API Docs</h1>
            <ul>
              <li><a href="api-reference.html">API Reference</a></li>
              <li><a href="https://github.com/${{ github.repository }}">GitHub Repo</a></li>
            </ul>
          </body>
          </html>
          EOF

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
