name: Vale Practice2

on:
  workflow_dispatch: # allows you to trigger it manually from GitHub

jobs:
  print-info:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Print GitHub username and Repo details
        run: |
          echo "GitHub Username: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"

      - name: Confirm Vale installation
        uses: errata-ai/vale-action@v2.1.1
     
